# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AR Demo App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for AR Demo App
  pod 'Mapbox-iOS-SDK', '3.3.5'
end
